### PR TITLE
str.partition(), rpartition(), startswith(), format()

### PR DESCRIPTION
**Pull request by cclauss**
You can now type `python spideyscrape.py http://my.favorite.url` or in Pythonista, tap and _hold_ the run button to type `http://my.favorite.url`.

### CODE REVIEW

**Comment by paultopia** [comment]
Thanks!  This looks good, with one exception: the changes to `getPage()` aren't quite right.  The purpose of `getPage()` is to make a beautiful soup object out of the original url passed in, and return that plus a version of the url with any 'document.htm' or 'document.html' stripped off the end.  

So `getPage('http://foo.bar/book/ToC.html')` ought to return `(makeSoup('http://foo.bar/book/ToC.html'), 'http://foo.bar/book/')`.  As I read your code (note to self, really need to write a test suite if there are going to be lots of people making contribs here), `getPage('http://foo.bar/book/ToC.html')` would actually return `(makeSoup('ToC.html'), 'ToC.html')`.  

Other than that, I think it's ready to merge.

**Comment by cclauss** [comment]
The fix is in there but GitHub seems unable to show a diff..

**Comment by paultopia** [comment]
Weird.  Let's see what happens if I merge it.  :-)

**Comment by paultopia** [comment]
All seems to be well despite github's quirks.  Thanks for the mods!

**Pull request merged**
